
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      mvc:
        routes:
          - id: customer-service
            uri: lb:http://CUSTOMER-SERVICE
            predicates:
              - Path=/customers/**
          - id: order-service
            uri: lb:http://ORDER-SERVICE
            predicates:
              - Path=/orders/**
              - Path=/order-line/**
          - id: product-service
            uri: lb:http://PRODUCT-SERVICE
            predicates:
              - Path=/products/**
              - Path=/category/**
          - id: payment-service
            uri: lb:http://PAYMENT-SERVICE
            predicates:
              - Path=/payment/**
server:
  port: 8086
