eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
          - id: customer-service
            uri: lb:http://CUSTOMER-SERVICE
            predicates:
              - Path=/customers/**
          - id: order-service
            uri: lb:http://ORDER-SERVICE
            predicates:
              - Path=/orders/**, /order-line/**
          - id: product-service
            uri: lb:http://PRODUCT-SERVICE
            predicates:
              - Path=/products/**, /category/**
          - id: payment-service
            uri: lb:http://PAYMENT-SERVICE
            predicates:
              - Path=/payment/**
server:
  port: 8086
management:
  tracing:
    sampling:
      probability: 1.0
